camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks

spring:
  datasource:
    url: jdbc:h2:file:~/data/camunda
    username: sa
    password: password
    driverClassName: org.h2.Driver