camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks

spring:
  datasource:
    url: jdbc:h2:file:~/data/camunda
    username: sa
    password: password
    driverClassName: org.h2.Driver


strapi:
  token: 7d7da039d52cbe9e2ac9fa730e0ae9257717dc209b956ae2efcafeb35671bd1725c08388f42bf081ba6c3bf20d0ae6b250272a201b15cb39101aa2fbb9baf21271caf616d20439a62ccd181a7c6a18f1b71f9dfa4f77351453d3c595fbf1710b56f36c7b5c39369a0e7c78b6e7a235abba789560e940cfefa0a455326037f7eb
  url:
    api: http://localhost:1337/api/
    orders: http://localhost:1337/api/orders/
    infos: http://localhost:1337/api/infos/
    items: http://localhost:1337/api/items/
    organisations: http://localhost:1337/api/organisations/

directus:
  token: _uakqMqYsUFnJfhDWpqHJ6w18z2mmst4
  url:
    item: http://localhost:8055/items/item/
    item_order: http://localhost:8055/items/item_order/
    task: http://localhost:8055/items/task/
    contract: http://localhost:8055/items/contract/
    order_event: http://localhost:8055/items/order_event
    type: http://localhost:8055/items/type?fields=id,name,prefix
    bill: http://localhost:8055/items/bill

elastic:
  url: http://localhost:9200/

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
